[window]
width = 600
height = 700
anchor = "center"
margin_top = 0
margin_bottom = 0
margin_left = 0
margin_right = 0
show_descriptions = false
show_paths = false
show_icons = true
show_search = true
show_actions = false
show_border = true
border_width = 2
use_gtk_colors = false
use_custom_css = false
max_entries = 50

[window.custom_navigate_keys]
up = "k"
down = "j"
delete_word = "h"

[theme.colors]
window_bg = "#231919"
search_bg = "#E5B750"
search_bg_focused = "#E5B750"
item_bg = "#231919"
item_bg_hover = "#E5B750"
item_bg_selected = "#E5B750"
search_text = "#eee1c9"
search_caret = "#eee1c9"
item_name = "#eee1c9"
item_name_selected = "#eee1c9"
item_description = "#eee1c9"
item_description_selected = "#eee1c9"
item_path = "#eee1c9"
item_path_selected = "#eee1c9"
border = "#E5B750"

[theme.corners]
window = 5
search = 8
list_item = 8

[theme.spacing]
search_margin = 12
search_padding = 12
item_margin = 6
item_padding = 4

[theme.typography]
search_font_size = 16
item_name_size = 14
item_description_size = 12
item_path_size = 12
item_path_font_family = "monospace"

[debug]
disable_auto_focus = false
enable_logging = false

[dmenu]
allow_invalid = false
case_sensitive = false

[web_search]
enabled = false
engine = "duckduckgo"
prefixes = []

[calculator]
enabled = false
